CREATE SCHEMA IF NOT EXISTS loja;
CREATE TABLE IF NOT EXISTS loja.register(
	id_reg INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	profileimg VARCHAR(50) NOT NULL DEFAULT 'noimage.jpg',
	name VARCHAR(255) NOT NULL DEFAULT '',
	age INT(255) NOT NULL DEFAULT '0',
	email VARCHAR(50) NOT NULL DEFAULT '',
	wallet VARCHAR(255) DEFAULT '0',
	password VARCHAR(8) NOT NULL DEFAULT '',
	c_password VARCHAR(8) NOT NULL DEFAULT ''

);
